// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBaiW0G0akhDm7Zp6I9Jmm_SCCHJgRMvk',
    appId: '1:972609470499:web:7df851b9603031a4b07196',
    messagingSenderId: '972609470499',
    projectId: 'album-9cdc6',
    authDomain: 'album-9cdc6.firebaseapp.com',
    storageBucket: 'album-9cdc6.appspot.com',
    measurementId: 'G-RVLLGS0R3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm4wVxTB9as4tJmxDds3140DkCqHrFvAQ',
    appId: '1:972609470499:android:0924c5306b55a7b6b07196',
    messagingSenderId: '972609470499',
    projectId: 'album-9cdc6',
    storageBucket: 'album-9cdc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEAT7Rbav-ys0cCsifjXRxQ-0L1Z7Udao',
    appId: '1:972609470499:ios:c7420b4f1b936900b07196',
    messagingSenderId: '972609470499',
    projectId: 'album-9cdc6',
    storageBucket: 'album-9cdc6.appspot.com',
    iosBundleId: 'com.example.pizza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEAT7Rbav-ys0cCsifjXRxQ-0L1Z7Udao',
    appId: '1:972609470499:ios:c997ecd1530cd5b0b07196',
    messagingSenderId: '972609470499',
    projectId: 'album-9cdc6',
    storageBucket: 'album-9cdc6.appspot.com',
    iosBundleId: 'com.example.pizza.RunnerTests',
  );
}
